name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
        - '**'
jobs:
  Test:
    if: false #temporary
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Setup NodeJS
        uses: actions/setup-node@v7
      - name: Npm Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
  Build:
    runs-on: ubuntu-latest
    # needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Docker build
        run: |
          docker build --progress=plain -t ghostfolio .
      - name: Setup AWS creds
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: ghostfolio
          image: yuratabghostfolio:latest





